<?php

namespace backend\widgets;

use yii\base\Widget;
use common\traits\ImageTrait;
use common\models\User;
use Yii;

class updateAvatars extends Widget
{
    use  ImageTrait;
    public $namePath;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $userModel = User::find()->select('id, email')->where(['id' => Yii::$app->user->identity->id])->one();
        $id = $userModel['id'];
        $email = substr($userModel['email'], 0, strpos($userModel['email'], '@'));
        $path = $_SERVER['DOCUMENT_ROOT'] . '/backend/web/images/uploadFiles/';
        $nameDir = $email.'_'.$id;
        $this->getNameFile($path, $nameDir);
        $this->namePath = $nameDir .'/'. $this->getNameFile($path, $nameDir)[2];
    }

    public function run()
    {
        return $this->namePath;
    }
}