<?php

namespace frontend\widgets;

use yii\base\Widget;
use common\models\basket\Basket;
use Yii;

class countBasket extends Widget {

    public $count;
    public $basket;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->basket = new Basket();
    }

    public function run()
    {
        if (!is_null($this->basket->getBasket())) {
            return $this->basket->getCountBasket();
        }
    }
}
